CREATE TABLE Products (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Code INTEGER NOT NULL,
    Name TEXT NOT NULL,
    Price REAL NOT NULL,
    EntryDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Brand TEXT NOT NULL,
    Stock INTEGER NOT NULL,
);

