CREATE TABLE INVOICES (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Number INTEGER NOT NULL UNIQUE,
    Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    TotalAmount REAL NOT NULL,
    UserId INTEGER NOT NULL,
    PaymentMethodId INTEGER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (PaymentMethodId) REFERENCES PaymentMethods(Id)
);

