CREATE TABLE Products (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Code TEXT NOT NULL,
    Name TEXT NOT NULL,
    Price REAL NOT NULL,
    EntryDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Brand TEXT NOT NULL,
    Stock REAL NOT NULL
);

